nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*'] # Autorise les requêtes du front-end
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization']
        allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_credentials: true
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Authorization']
            allow_methods: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE']
