security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login_check
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login_check  # Le point de terminaison pour vérifier les identifiants
                username_path: email          # Le chemin JSON pour l'email (c'est-à-dire le nom de champ dans la requête JSON)
                password_path: password 

        main:
            lazy: true
            provider: app_user_provider
            security: false
            

        # Firewall pour l'API avec authentification par jeton d'accès
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            custom_authenticators:
                -token_handler: App\Security\AccessTokenHandler

    access_control:
        # Autoriser l'accès anonyme pour /api/login_check
          - { path: ^/admin, roles: ROLE_ADMIN }
          - { path: ^/api, roles: ROLE_USER }
