security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email  # Identifiant d'authentification

    firewalls:
        # Firewall pour l'authentification via json_login pour générer le token
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

        # Firewall pour les requêtes API protégées qui nécessitent un token JWT
     

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    access_control:
        - { path: ^/api/utilisateurs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api, roles: ROLE_USER  }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/me, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/test-token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
